// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzeqhAsBXNBmZk4fBvM2WbkZD9k7O-88I',
    appId: '1:288029868075:web:51f162db9aff87537c6a6e',
    messagingSenderId: '288029868075',
    projectId: 'freeworkoutapss',
    authDomain: 'freeworkoutapss.firebaseapp.com',
    storageBucket: 'freeworkoutapss.appspot.com',
    measurementId: 'G-7TYGSG3PF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5EK90Msx6sro16kz2hls7bZvivOXFqmU',
    appId: '1:288029868075:android:35475b77215d0b887c6a6e',
    messagingSenderId: '288029868075',
    projectId: 'freeworkoutapss',
    storageBucket: 'freeworkoutapss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkqcDkAmIbL6Vm2xpUz-mgk0yGq2iQndc',
    appId: '1:288029868075:ios:17d443842c2de2837c6a6e',
    messagingSenderId: '288029868075',
    projectId: 'freeworkoutapss',
    storageBucket: 'freeworkoutapss.appspot.com',
    iosClientId: '288029868075-1qdo8lld9euq5q4r17ddf7ebnkbg5qvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeWorkoutApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkqcDkAmIbL6Vm2xpUz-mgk0yGq2iQndc',
    appId: '1:288029868075:ios:17d443842c2de2837c6a6e',
    messagingSenderId: '288029868075',
    projectId: 'freeworkoutapss',
    storageBucket: 'freeworkoutapss.appspot.com',
    iosClientId: '288029868075-1qdo8lld9euq5q4r17ddf7ebnkbg5qvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeWorkoutApps',
  );
}
